### PR TITLE
MapSlicer

### PR DESCRIPTION
**Pull request by activityworkshop**
I've made a few changes to simplify and chop out unnecessary code.  In particular, I removed the menu as it only linked to online resources from maptiler.org.  And I changed the directory picker for selecting the output directory, as firstly it didn't work at all due to a Gtk bug, and secondly it required a "gtk2 hack" to create the directory and delete it again.
I also updated the translation files, maybe we can get some other languages started.

### CODE REVIEW

**Comment by kalxas** [comment]
Thanks!
Should I revert rc1 or bump to rc2?

**Comment by kalxas** [comment]
http://wiki.osgeo.org/wiki/MapSlicer

**Comment by activityworkshop** [comment]
I'm not sure what you mean by reverting rc1.  I don't mind whether you call it rc1 or rc2, I'll leave that up to you.

**Comment by kalxas** [comment]
ok thanks :)

**Pull request merged**
